name: Check directory and send an email
on:
  workflow_dispatch:     #trigger manually

jobs:
  check_directory:
    runs-on: ubuntu-latest
    outputs:
      file_missing: ${{ steps.file_check.outputs.file_missing}}
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: check directory
        id: file_check
        run: |
          FILE_PATH="characters/Dockerfile"
          FILE_MISSING=false
          if [[ -f "$FILE_PATH" ]]; then
            echo "File FOUND. All good."
          else
            echo "File NOT FOUND. Email will be sent."
            echo "FILE_MISSING=true" >> "$GITHUB_OUTPUT"
          fi
          
  send_email:
    runs-on: ubuntu-latest
    needs: check_directory
    if: needs.check_directory.outputs.file_missing == 'true'
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: send mail
        env:
          EMAIL: ${{secrets.GMAIL_EMAIL}}
          PSWRD: ${{secrets.GMAIL_PASSWORD}}
        run: python send-email.py
          

          

                